<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="26574" started-at="2020-06-02T00:46:40 IST" finished-at="2020-06-02T00:47:07 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="26574" started-at="2020-06-02T00:46:40 IST" finished-at="2020-06-02T00:47:07 IST">
      <class name="com.sps.dc4.testscripts.GmailAutomationTest">
        <test-method status="PASS" signature="setDriver()[pri:0, instance:com.sps.dc4.testscripts.GmailAutomationTest@2b552920]" name="setDriver" is-config="true" duration-ms="23500" started-at="2020-06-02T00:46:40 IST" finished-at="2020-06-02T00:47:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setDriver -->
        <test-method status="FAIL" signature="irnit2()[pri:1, instance:com.sps.dc4.testscripts.GmailAutomationTest@2b552920]" name="irnit2" duration-ms="3021" started-at="2020-06-02T00:47:04 IST" finished-at="2020-06-02T00:47:07 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.sps.dc4.pages.LoginPage.login(LoginPage.java:52)
at com.sps.dc4.testscripts.GmailAutomationTest.irnit2(GmailAutomationTest.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$247/214187874.accept(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- irnit2 -->
      </class> <!-- com.sps.dc4.testscripts.GmailAutomationTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
